### PR TITLE
Implement configurable reload trigger debouncing

### PR DESCRIPTION
**Pull request by ghost**
This PR implements debouncing for reload triggers (so when multiple files are changed or multiple API calls to /api-reloadserver/trigger-reload are made in rapid succession, the page will only reload once). The debounce interval is configurable via the command line parameter `--debounce-interval, -D` and defaults to 500 ms.

(P.S. If you're wondering why I'm making this pull request 17 hours after the commit, it's because `hwclock` was out of sync in WSL2 and I actually committed ~20 minutes ago)

### CODE REVIEW

**Comment by Densaugeo** [comment]
This looks like a useful convenience.

One possible issue I see is that this design adds latency (500 ms with the default). What do you think the shortest default that still offers reasonable debouncing would be? It's not something I can easily test, since I'm not familiar with webpack/react/etc. and the timing of their filesystem writes.

Also, please add some tests. `test_reload_by_api_multiple()` and `test_reload_by_watchdog_multiple()` might be good examples to pull from.

**Comment by ghost** [comment]
The additional delay is actually part of the reason why I want this change. In my case files a source file (that is also being watched) is recompiled automatically, causing the produced HTML file to be updated slightly after that. If the reload event trigger right on the first source file modification, the output file will get written while the browser is still reloading, causing it to still load the old version of the file.

I realise now that the proper way to address would not be to debounce file changes but instead to only reload the page when that specific file is modified, instead of reloading *all* pages whenever *any* file is modified.

Debouncing is still important though, because when the same file is rapidly written to, the first issue would still occur.

As for the chosen interval, I have no idea what would be a good default value. It's most likely different for every use case, so I chose 500ms as a default so you shouldn't have to worry about it in most cases I think, but ultimately it will depend on browser reload times, which will be different for every file/machine/browser so it's hard to make a good estimate.

**Comment by Densaugeo** [comment]
There's also some value to getting better behavior out of the box, so it works reasonably well without people having to find/remember the right set of arguments.

I did some testing with the Rust-based build chain I'm using wasm modules, and in that case times of a hundred ms or more between filesystem events are fairly common, so 500 ms seems as good a default as any. In my investigation I noticed a couple things:

- There is currently a debounce time on the client side. The injected script tag waits 1000 ms before beginning to listen to reload events (I'd forgotten about this). This is the "reload instantly and then have a blackout time" approach that we already agreed was not as good (it can also make network logs messy). The client-side debounce should be removed in favor of the server-side one.

- Some text editors can generate dozens of filesystem events every time you hit ctrl+s. This is pretty much never desirable behavior, so I propose a requiring a minimum debounce time of 10 ms.

- Triggering a reload by HTTP request should bypass the debounce time, since this is an explicit command (basically, call `notify_reload()` instead of `trigger_reload()`.

- The distinction between `notify_reload()` and `trigger_reload()` isn't obvious from the names. We should find clearer names.

**Comment by Densaugeo** [comment]
Hey, saw you withdrew your other pull request. Are you planning to update this one or make a new one?

**Comment by ghost** [comment]
Hi, yeah I was working on that indeed (and fighting with git a bit) but
kind of forgot about it.  
  
Another thing I wanted to implement was to reload only the page that is
changed, however I think some refactoring is needed for that as it will
require sending the filename to the webpage. I found an older project of
mine that included a small version of a reload server written in Rust where
I used an EventSource for the server-client communication, but I'm not sure
how to implement that in Python yet so I'll have to look into that.  
  
Also, do you think it would be a good idea to add a command line flag for
executing a build script as well as reloading the webpage when files are
changed or would that be out of scope for this project? The way I use this
package currently is to have a script that compiles AsciiDoc files to HTML
whenever they're changed, and then use reloadserver to reload the HTML
pages in the browser. Since tasks like these are likely fairly common (I
think) I thought it might be neat to combine it into a single command, so
you don't need to have multiple file watchers running at the same time.

**Comment by Densaugeo** [comment]
It sounds like you're experiencing some scope creep. Regarding the new features you propose:

1 - Selective reloading of changed files only. This would be quite complicated - you'd need to know which pages depended on which files to know when to reload any given page. Since web pages can depend on many different file types, and these dependencies are often dynamic, this would be a major undertaking, and would likely always be a little error-prone. In addition, I try to keep caching to a minimum on reloadserver, and force complete reloads where possible to avoid serving old versions of pages.

2 - Option to run a build script. This can already be done with tools like inotify, and reloadserver can be triggered by a curl command at the end of your build script. The gain here would be a fairly minor convenience, and would only benefit users who take the time to read the available options...who are probably the sort who already know how to use inotify.

Let's focus on implementing your earlier proposals, which are simpler to implement and offer a clearer benefit.

**Comment by ghost** [comment]
That's fair. I've addressed your previous points, and I think this feature should be implemented fully now.

I'm not sure how I should write the tests though, since this is about timing, and it looks like the current testing code doesn't deal with that yet.

**Comment by Densaugeo** [comment]
Alright, looking a lot better! I'll go ahead and merge this and add the test cases while I'm trying it out.

**Pull request merged**
